[package]
name = "intershell"
version = "0.1.0"
authors = ["LackingInGrav1tas <42680395+LackingInGrav1tas@users.noreply.github.com>"]
edition = "2018"

[dependencies]
toml = "0.5.3"
crossterm = "0.20.0"
